import { People, SelfieEvent } from "./types";

const dummyPeople: People = [
  {
    _id: "1",
    events: {
      created: [],
      participating: [],
    },
    avatar: "https://example.com/avatar1.jpg",
    friends: [],
    name: "Alice",
    surname: "Johnson",
    email: "alice@example.com",
    phoneNumber: "123-456-7890",
    username: "alice",
    password: "password",
    birthDate: new Date("1990-01-01"),
    address: "123 Main St",
    city: "Springfield",
    state: "IL",
    zip: "62701",
    country: "USA",
  },
  {
    _id: "2",
    events: {
      created: [],
      participating: [],
    },
    avatar: "https://example.com/avatar2.jpg",
    friends: [],
    name: "Bob",
    surname: "Smith",
    email: "bob@example.com",
    phoneNumber: "234-567-8901",
    username: "bob",
    password: "password",
    birthDate: new Date("1985-05-15"),
    address: "456 Elm St",
    city: "Shelbyville",
    state: "IL",
    zip: "62565",
    country: "USA",
  },
  {
    _id: "3",
    events: {
      created: [],
      participating: [],
    },
    avatar: "https://example.com/avatar3.jpg",
    friends: [],
    name: "Charlie",
    surname: "Brown",
    email: "charlie@example.com",
    phoneNumber: "345-678-9012",
    username: "charlie",
    password: "password",
    birthDate: new Date("1988-09-30"),
    address: "789 Oak St",
    city: "Capital City",
    state: "IL",
    zip: "62701",
    country: "USA",
  },
  {
    _id: "4",
    events: {
      created: [],
      participating: [],
    },
    avatar: "https://example.com/avatar4.jpg",
    friends: [],
    name: "Diana",
    surname: "Prince",
    email: "diana@example.com",
    phoneNumber: "456-789-0123",
    username: "diana",
    password: "password",
    birthDate: new Date("1992-07-01"),
    address: "101 Pine St",
    city: "Ogdenville",
    state: "IL",
    zip: "62271",
    country: "USA",
  },
];

// Set up friend relationships
dummyPeople[0].friends = [dummyPeople[1], dummyPeople[2]];
dummyPeople[1].friends = [dummyPeople[0], dummyPeople[3]];
dummyPeople[2].friends = [dummyPeople[0], dummyPeople[3]];
dummyPeople[3].friends = [dummyPeople[1], dummyPeople[2]];

const dummyEvents: SelfieEvent[] = [
  {
    title: "Beach Party",
    participants: [dummyPeople[0], dummyPeople[1], dummyPeople[2]],
    dtstart: new Date("2024-08-15T14:00:00"),
    dtend: new Date("2024-08-15T20:00:00"),
    summary: "A fun beach party with friends.",
    uid: "event-1",
    sequence: 1,
    status: "confirmed",
    location: "Beach",
    description: "Join us for a beach party with games and food.",
    URL: "https://example.com/beach-party",
    categories: ["party"],
    transp: "OPAQUE",
    rrule: {
      freq: { type: "weekly", enum: ["daily", "weekly", "monthly", "yearly"] },
      interval: 1,
      bymonth: 8,
      bymonthday: 15,
    },
    dtstamp: new Date().toISOString(),
    geo: [40.7128],
  },
  {
    title: "Movie Night",
    participants: [dummyPeople[1], dummyPeople[3]],
    dtstart: new Date("2024-08-20T19:00:00"),
    dtend: new Date("2024-08-20T23:00:00"),
    summary: "A night of movies and popcorn.",
    uid: "event-2",
    sequence: 1,
    status: "confirmed",
    location: "Bob's House",
    description: "Watch movies and enjoy snacks.",
    URL: "https://example.com/movie-night",
    categories: ["movie"],
    transp: "OPAQUE",
    rrule: {
      freq: { type: "weekly", enum: ["daily", "weekly", "monthly", "yearly"] },
      interval: 1,
      bymonth: 8,
      bymonthday: 20,
    },
    dtstamp: new Date().toISOString(),
    geo: [40.7122],
  },
  {
    title: "Picnic in the Park",
    participants: dummyPeople,
    dtstart: new Date("2024-08-25T12:00:00"),
    dtend: new Date("2024-08-25T16:00:00"),
    summary: "A relaxing picnic in the park.",
    uid: "event-3",
    sequence: 1,
    status: "confirmed",
    location: "Central Park",
    description: "Bring your own food and enjoy a picnic.",
    URL: "https://example.com/picnic",
    categories: ["picnic"],
    transp: "OPAQUE",
    rrule: {
      freq: { type: "weekly", enum: ["daily", "weekly", "monthly", "yearly"] },
      interval: 1,
      bymonth: 8,
      bymonthday: 25,
    },
    dtstamp: new Date().toISOString(),
    geo: [40.7128],
  },
];

const exportObj = { dummyPeople, dummyEvents };

export default exportObj;
