
# Use the official Node.js 20.0.0 image as a base image
FROM node:20.0.0

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application files
COPY . .

# Expose the application port (adjust this if necessary)
EXPOSE 3001

# Command to run the application
CMD ["npm", "start"]
