name: Check PR 

on:
  pull_request:
    branches: [develop-build]

  jobs:
    compile-clinet:
      runs-on: self-hosted

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20"

        - name: Create .env.local file
          run: |
            echo "${{ secrets.WEATHER_API }}" > client/.env.local

        - name: Compile client
          run: |
            cd client
            npm install
            npm run build
